"""empty message

Revision ID: 192a02f28460
Revises: 27bf6ef137d9
Create Date: 2020-06-04 20:01:25.755548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192a02f28460'
down_revision = '27bf6ef137d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('venue', 'imagelink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('imagelink', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venue', 'website')
    # ### end Alembic commands ###
