"""empty message

Revision ID: 91ea9e61bdde
Revises: 03966675ddc3
Create Date: 2020-06-04 19:07:59.342766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "91ea9e61bdde"
down_revision = "03966675ddc3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artist", "seeking_talent")
    op.drop_column("artist", "seeking_description")
    op.add_column(
        "venue", sa.Column("seeking_description", sa.String(length=500), nullable=True)
    )
    op.add_column("venue", sa.Column("seeking_talent", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("venue", "seeking_talent")
    op.drop_column("venue", "seeking_description")
    op.add_column(
        "artist",
        sa.Column(
            "seeking_description",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "artist",
        sa.Column("seeking_talent", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
